<a href="https://colab.research.google.com/github/Tanzeel-data/Practice/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

temps = np.array([
    # City 1
    [[30, 35], [31, 36],
     [29, 34], [32, 37],
      [33, 38], [34, 39], [35, 40]],

    # City 2
    [[25, 30], [26, 31], [27, 32], [28, 33], [29, 34], [30, 35], [31, 36]],

    # City 3
    [[20, 25], [21, 26], [22, 27], [23, 28], [24, 29], [25, 30], [26, 31]]
])

In [19]:
np.ndim(temps)

3

temps[temps > 35] = 35
print("Temperatures after replacement:")
print(temps)

In [20]:
np.shape(temps)

(3, 7, 2)

In [21]:
result = np.mean(temps, axis=(0,2))
print(result.shape)

(7,)


In [22]:

hottest = np.max(temps)
coldest = np.min(temps)

In [23]:
print(f"hottest: {hottest}")
print(f"coldest: {coldest}")

hottest: 40
coldest: 20


## highest avg temp city


In [24]:
city_avgs = np.mean(temps, axis=(1,2))
highest_avg = np.max(city_avgs)
hottest_city = np.argmax(city_avgs)
highest_avg
hottest_city


np.int64(0)

In [25]:
city_avgs

array([34.5, 30.5, 25.5])

## make 35+ = 35


In [28]:
np.clip(temps,None,35)

array([[[30, 35],
        [31, 35],
        [29, 34],
        [32, 35],
        [33, 35],
        [34, 35],
        [35, 35]],

       [[25, 30],
        [26, 31],
        [27, 32],
        [28, 33],
        [29, 34],
        [30, 35],
        [31, 35]],

       [[20, 25],
        [21, 26],
        [22, 27],
        [23, 28],
        [24, 29],
        [25, 30],
        [26, 31]]])

##* extract only evening temp from all cities*


In [31]:
evening_temp = temps[:,:,1]

In [32]:
even_temp

array([30, 36, 34, 32, 38, 34, 40, 30, 26, 32, 28, 34, 30, 36, 20, 26, 22,
       28, 24, 30, 26])

In [33]:
np.where(np.all(np.diff(temps[:, :, 0], axis=1) > 0, axis=1))[0]

array([1, 2])